### ISSUE TITLE
Numbers are displayed as blank spaces in all Android browsers

### ISSUE THREAD

**Issue by imfx77** [mrdrogdrog/twemoji-color-font#3]
@mrdrogdrog 
I tried supplying the web font on my site alongside pages that display emojis, in order to guarantee that they will look in the same way on all platforms and in all browsers. Which worked great.

There is only that tiny yet annoying problem that all android browsers I've tried don't show numbers  in the text of HTML elements that use the font. Instead blank spaces appear. Interestingly enough, special characters, cyrillic or chinese characters, etc. show just fine - it is only the number that vanish.

Haven't tested any iOS browsers, they might have a similar issue.

The screenshot below is from Samsung browser, but the same appears in Edge, Chrome and Mozilla on Android.
- The first line has an input element that uses the standard `sans-serif` font.
- The second line has a label element with the same text that uses the `twemoji` woff.
![image](https://github.com/user-attachments/assets/90405b1d-5303-40df-89f3-1e3a36fa5500)
This screenshot just shows that emojis in the second line are from `twemoji` font, and they differ from the standard Android supplied ones above.
![image](https://github.com/user-attachments/assets/49cb4a35-9278-4d38-a109-5ce5134b766b)

Any insights? What could be wrong?

**Comment by mrdrogdrog** [comment]
Huh. Fascinating. What is your css rule for this element? Especially: how did you specify font-family? Did you specify unicode-range?

**Comment by imfx77** [comment]
I use it like that to override some standard and system fonts:
```css
@font-face {
  font-family: "Emoji Font for WysiwygMDEditor";
  src: url('emojis.woff2') format('woff2');
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Emoji Font for WysiwygMDEditor", Helvetica, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Twemoji Mozilla", "Segoe UI Emoji", "Android Emoji", "Segoe UI Symbol" !important;
}
```
I don's specify a Unicode range. Should I? what range exactly?
If it was somehow stated that the font covers emoji symbols only it would make sense, but it covers almost any symbol, except for numbers. Actually, some more symbols like `*` and `#` also don't appear.

Just be aware that the if [twemoji-colr from mozilla](https://github.com/mozilla/twemoji-colr) is indeed your source, there are the same issues for their exported release TTF, so most likely it's their fault. I use [this online viewer](https://fontsee.com/) to test fonts easily.

**Comment by imfx77** [comment]
I just wanted to say that my initial claim is wrong - it's not about android browsers - those symbols are just missing from the font, no browser is able to show them ;/

**Comment by mrdrogdrog** [comment]
I tried to replicate the problem with minimal html code with
```css
@font-face {
  font-family: "roboto";
  src: url("/css/roboto.ttf");
}

@font-face {
  font-family: "twemoji";
  src: url("/css/twemoji.woff2") format("woff2");
}


body {
  font-family: "roboto", "twemoji";
}
```

and 

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
<p>Here are not 1, not 2 but 3 emojis: ❤️👽🎩</p>
</body>
</html>
```

and the outcome is as expected:

<img width="324" alt="image" src="https://github.com/user-attachments/assets/c0b70648-ac49-4f0f-b5d4-9ffe06a6af28">

Tbh this one font "Emoji Font for WysiwygMDEditor" looks pretty sus to me.
Why is "Emoji Font for WysiwygMDEditor" coming before your normal fonts? Why is it not at the end with the other emoji fonts? The fonts are used in order of definition and you have enough fonts there which have numbers defined.
